/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author kevin
 */
public class Interface_CRUD extends javax.swing.JFrame {

    /**
     * Creates new form Interface_CRUD
     */
    public Interface_CRUD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlbl_title_musica = new javax.swing.JLabel();
        jlbl_nome_musica = new javax.swing.JLabel();
        jfild_nome_musica = new javax.swing.JTextField();
        jlbl_genero_musica = new javax.swing.JLabel();
        jfield_genero_musica = new javax.swing.JTextField();
        jlbl_cantor_musica = new javax.swing.JLabel();
        jfield_cantor_musica = new javax.swing.JTextField();
        jlbl_feat_musica = new javax.swing.JLabel();
        jfield_feat_musica = new javax.swing.JTextField();
        jlbl_adiciona_musica = new javax.swing.JLabel();
        jlbl_nome_musica_2 = new javax.swing.JLabel();
        jfild_nome_musica_2 = new javax.swing.JTextField();
        jlbl_cantor_musica_2 = new javax.swing.JLabel();
        jfield_cantor_musica_2 = new javax.swing.JTextField();
        jlbl_genero_musica_2 = new javax.swing.JLabel();
        jfield_genero_musica_2 = new javax.swing.JTextField();
        jlbl_feat_musica_2 = new javax.swing.JLabel();
        jfield_feat_musica_2 = new javax.swing.JTextField();
        jfield_id_musica = new javax.swing.JTextField();
        jlbl_id_musica = new javax.swing.JLabel();
        jlbl_editar = new javax.swing.JLabel();
        jbutton_visualizar = new javax.swing.JButton();
        jbutton_adicionar1 = new javax.swing.JButton();
        jbutton_atualizar = new javax.swing.JButton();
        jbutton_remover = new javax.swing.JButton();
        jlbl_id_remov_visua = new javax.swing.JLabel();
        jfield_id_musica_remov_visua = new javax.swing.JTextField();
        jlbl_remov_visua = new javax.swing.JLabel();
        jlbl_nome_musica_visua = new javax.swing.JLabel();
        jlbl_nome_cantor_visua = new javax.swing.JLabel();
        jlbl_genero_musica_visua = new javax.swing.JLabel();
        jlbl_feat_musica_visua = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 750));
        setPreferredSize(new java.awt.Dimension(1200, 750));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(1192, 750));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbl_title_musica.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jlbl_title_musica.setText("Música");
        jPanel1.add(jlbl_title_musica, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, -1, -1));

        jlbl_nome_musica.setText("Nome da música:");
        jPanel1.add(jlbl_nome_musica, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jfild_nome_musica.setPreferredSize(new java.awt.Dimension(300, 60));
        jPanel1.add(jfild_nome_musica, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jlbl_genero_musica.setText("Gênero da música:");
        jPanel1.add(jlbl_genero_musica, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jfield_genero_musica.setPreferredSize(new java.awt.Dimension(300, 60));
        jPanel1.add(jfield_genero_musica, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jlbl_cantor_musica.setText("Cantor da música:");
        jPanel1.add(jlbl_cantor_musica, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jfield_cantor_musica.setPreferredSize(new java.awt.Dimension(300, 60));
        jfield_cantor_musica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfield_cantor_musicaActionPerformed(evt);
            }
        });
        jPanel1.add(jfield_cantor_musica, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jlbl_feat_musica.setText("Feat (se houver):");
        jPanel1.add(jlbl_feat_musica, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jfield_feat_musica.setPreferredSize(new java.awt.Dimension(300, 60));
        jPanel1.add(jfield_feat_musica, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        jlbl_adiciona_musica.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jlbl_adiciona_musica.setText("Adicionar música");
        jPanel1.add(jlbl_adiciona_musica, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        jlbl_nome_musica_2.setText("Nome da música:");
        jPanel1.add(jlbl_nome_musica_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, -1, -1));

        jfild_nome_musica_2.setPreferredSize(new java.awt.Dimension(300, 60));
        jPanel1.add(jfild_nome_musica_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, -1, -1));

        jlbl_cantor_musica_2.setText("Cantor da música:");
        jPanel1.add(jlbl_cantor_musica_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, -1, -1));

        jfield_cantor_musica_2.setPreferredSize(new java.awt.Dimension(300, 60));
        jfield_cantor_musica_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfield_cantor_musica_2ActionPerformed(evt);
            }
        });
        jPanel1.add(jfield_cantor_musica_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, -1, -1));

        jlbl_genero_musica_2.setText("Gênero da música:");
        jPanel1.add(jlbl_genero_musica_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, -1, -1));

        jfield_genero_musica_2.setPreferredSize(new java.awt.Dimension(300, 60));
        jPanel1.add(jfield_genero_musica_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, -1, -1));

        jlbl_feat_musica_2.setText("Feat (se houver):");
        jPanel1.add(jlbl_feat_musica_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 520, -1, -1));

        jfield_feat_musica_2.setPreferredSize(new java.awt.Dimension(300, 60));
        jPanel1.add(jfield_feat_musica_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 540, -1, -1));

        jfield_id_musica.setPreferredSize(new java.awt.Dimension(300, 60));
        jPanel1.add(jfield_id_musica, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 300, 60));

        jlbl_id_musica.setText("ID:");
        jPanel1.add(jlbl_id_musica, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, -1, -1));

        jlbl_editar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jlbl_editar.setText("Editar");
        jPanel1.add(jlbl_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, -1, -1));

        jbutton_visualizar.setText("Visualizar");
        jbutton_visualizar.setPreferredSize(new java.awt.Dimension(100, 30));
        jbutton_visualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton_visualizarActionPerformed(evt);
            }
        });
        jPanel1.add(jbutton_visualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 230, -1, -1));

        jbutton_adicionar1.setText("Adicionar");
        jbutton_adicionar1.setPreferredSize(new java.awt.Dimension(100, 30));
        jbutton_adicionar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton_adicionar1ActionPerformed(evt);
            }
        });
        jPanel1.add(jbutton_adicionar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 530, -1, -1));

        jbutton_atualizar.setText("Atualizar");
        jbutton_atualizar.setPreferredSize(new java.awt.Dimension(100, 30));
        jbutton_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton_atualizarActionPerformed(evt);
            }
        });
        jPanel1.add(jbutton_atualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 630, -1, -1));

        jbutton_remover.setText("Remover");
        jbutton_remover.setPreferredSize(new java.awt.Dimension(100, 30));
        jbutton_remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton_removerActionPerformed(evt);
            }
        });
        jPanel1.add(jbutton_remover, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 230, -1, -1));

        jlbl_id_remov_visua.setText("ID:");
        jPanel1.add(jlbl_id_remov_visua, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 120, -1, -1));

        jfield_id_musica_remov_visua.setPreferredSize(new java.awt.Dimension(300, 60));
        jPanel1.add(jfield_id_musica_remov_visua, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 140, -1, -1));

        jlbl_remov_visua.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jlbl_remov_visua.setText("Remover/Visualizar");
        jPanel1.add(jlbl_remov_visua, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 80, -1, -1));

        jlbl_nome_musica_visua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlbl_nome_musica_visua.setText("nome musica");
        jPanel1.add(jlbl_nome_musica_visua, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 320, -1, -1));

        jlbl_nome_cantor_visua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlbl_nome_cantor_visua.setText("nome cantor");
        jPanel1.add(jlbl_nome_cantor_visua, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 350, -1, -1));

        jlbl_genero_musica_visua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlbl_genero_musica_visua.setText("genero");
        jPanel1.add(jlbl_genero_musica_visua, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 380, -1, -1));

        jlbl_feat_musica_visua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlbl_feat_musica_visua.setText("feat");
        jPanel1.add(jlbl_feat_musica_visua, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 410, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jfield_cantor_musicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfield_cantor_musicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfield_cantor_musicaActionPerformed

    private void jfield_cantor_musica_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfield_cantor_musica_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfield_cantor_musica_2ActionPerformed

    private void jbutton_visualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton_visualizarActionPerformed
        // TODO add your handling code here:
        try {
            Connection conexao = null;
            PreparedStatement statement = null;
            
            String url = "jdbc:mysql://localhost:3306/musicas_boas";
            String usuario = "root";
            String senha = "";
            
            conexao = DriverManager.getConnection(url, usuario, senha);
            
            String sql = "SELECT nome_musica, cantor_musica, genero_musica, feat_musica FROM musica WHERE id_musica = ?";
            
            statement = conexao.prepareStatement(sql);
            statement.setString(1, jfield_id_musica_remov_visua.getText());
            
            ResultSet resultSet = statement.executeQuery();
            
            if (resultSet.next()) {
                String nome_musica = resultSet.getString("nome_musica");
                String cantor_musica = resultSet.getString("cantor_musica");
                String genero_musica = resultSet.getString("genero_musica");
                String feat_musica = resultSet.getString("feat_musica");
                jlbl_nome_musica_visua.setText("Nome da música: " + nome_musica);
                jlbl_nome_cantor_visua.setText("Cantor da música: " + cantor_musica);
                jlbl_genero_musica_visua.setText("Gênero da música: " + genero_musica);
                jlbl_feat_musica_visua.setText("Feat da música: " + feat_musica);
                        
                jlbl_nome_musica_visua.setVisible(true);
                jlbl_nome_cantor_visua.setVisible(true);
                jlbl_genero_musica_visua.setVisible(true);
                jlbl_feat_musica_visua.setVisible(true);
                
            }
            else {
                jlbl_nome_musica_visua.setText("Música não encontrada.");
                jlbl_nome_cantor_visua.setText("Cantor não encontrado.");
                jlbl_genero_musica_visua.setText("Gênero não encontrado.");
                jlbl_feat_musica_visua.setText("Feat não encontrado.");
            }
            
            resultSet.close();
            statement.close();
            conexao.close();
            
        } catch (SQLException e) {
            System.out.println("Deu esse erro aqui ô: " + e.getMessage());
        }
        
    }//GEN-LAST:event_jbutton_visualizarActionPerformed

    private void jbutton_adicionar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton_adicionar1ActionPerformed
        // TODO add your handling code here:
        try {
            Connection conexao = null;
            PreparedStatement statement = null;
            
            String url = "jdbc:mysql://localhost:3306/musicas_boas";
            String usuario = "root";
            String senha = "";
            
            conexao = DriverManager.getConnection(url, usuario, senha);
            
            String sql = "INSERT INTO musica (nome_musica, cantor_musica, genero_musica, feat_musica) VALUES (?, ?, ?, ?)";
            
            statement = conexao.prepareStatement(sql);
            statement.setString(1, jfild_nome_musica.getText()); // Nome da música
            statement.setString(2, jfield_cantor_musica.getText()); // Cantor da música
            statement.setString(3, jfield_genero_musica.getText()); // Gênero da música
            statement.setString(4, jfield_feat_musica.getText()); // Feat da música
            
            statement.executeUpdate();
            System.out.println("Musica adicionada com sucesso!");
            
        } catch (SQLException e) {
            System.out.println("Deu esse erro aqui ô: " + e.getMessage());
        }
    }//GEN-LAST:event_jbutton_adicionar1ActionPerformed

    private void jbutton_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton_atualizarActionPerformed
        // TODO add your handling code here:
        try {
            Connection conexao = null;
            PreparedStatement statement = null;
            
            String url = "jdbc:mysql://localhost:3306/musicas_boas";
            String usuario = "root";
            String senha = "";
            
            conexao = DriverManager.getConnection(url, usuario, senha);
            
            String sql = "UPDATE musica SET nome_musica = ?, cantor_musica = ?, genero_musica = ?, feat_musica = ? WHERE id_musica = ?";
            
            statement = conexao.prepareStatement(sql);
            statement.setString(1, jfild_nome_musica_2.getText()); // Nome da música atualizada
            statement.setString(2, jfield_cantor_musica_2.getText()); // Cantor da música atualizado
            statement.setString(3, jfield_genero_musica_2.getText()); // Gênero da música atualizado
            statement.setString(4, jfield_feat_musica_2.getText()); // Feat da música atualizado
            statement.setString(5, jfield_id_musica.getText()); // id_musica a ser atualizado
            
            statement.executeUpdate();
            System.out.println("Musica modificada com sucesso.");
            
        } catch (SQLException e) {
            System.out.println("Deu esse erro aqui ô: " + e.getMessage());
        }
    }//GEN-LAST:event_jbutton_atualizarActionPerformed

    private void jbutton_removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton_removerActionPerformed
        // TODO add your handling code here:
        try {
            Connection conexao = null;
            PreparedStatement statement = null;
            
            String url = "jdbc:mysql://localhost:3306/musicas_boas";
            String usuario = "root";
            String senha = "";
            
            conexao = DriverManager.getConnection(url, usuario, senha);
            
            String sql = "DELETE FROM musica WHERE id_musica = ?";
            
            statement = conexao.prepareStatement(sql);
            statement.setString(1, jfield_id_musica_remov_visua.getText());
            
            statement.executeUpdate();
            System.out.println("Musica removida com sucesso.");
            
        } catch (SQLException e) {
            System.out.println("Deu esse erro aqui ô: " + e.getMessage());
        }
    }//GEN-LAST:event_jbutton_removerActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        jlbl_nome_musica_visua.setVisible(false);
        jlbl_nome_cantor_visua.setVisible(false);
        jlbl_genero_musica_visua.setVisible(false);
        jlbl_feat_musica_visua.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface_CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface_CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface_CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface_CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface_CRUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbutton_adicionar1;
    private javax.swing.JButton jbutton_atualizar;
    private javax.swing.JButton jbutton_remover;
    private javax.swing.JButton jbutton_visualizar;
    private javax.swing.JTextField jfield_cantor_musica;
    private javax.swing.JTextField jfield_cantor_musica_2;
    private javax.swing.JTextField jfield_feat_musica;
    private javax.swing.JTextField jfield_feat_musica_2;
    private javax.swing.JTextField jfield_genero_musica;
    private javax.swing.JTextField jfield_genero_musica_2;
    private javax.swing.JTextField jfield_id_musica;
    private javax.swing.JTextField jfield_id_musica_remov_visua;
    private javax.swing.JTextField jfild_nome_musica;
    private javax.swing.JTextField jfild_nome_musica_2;
    private javax.swing.JLabel jlbl_adiciona_musica;
    private javax.swing.JLabel jlbl_cantor_musica;
    private javax.swing.JLabel jlbl_cantor_musica_2;
    private javax.swing.JLabel jlbl_editar;
    private javax.swing.JLabel jlbl_feat_musica;
    private javax.swing.JLabel jlbl_feat_musica_2;
    private javax.swing.JLabel jlbl_feat_musica_visua;
    private javax.swing.JLabel jlbl_genero_musica;
    private javax.swing.JLabel jlbl_genero_musica_2;
    private javax.swing.JLabel jlbl_genero_musica_visua;
    private javax.swing.JLabel jlbl_id_musica;
    private javax.swing.JLabel jlbl_id_remov_visua;
    private javax.swing.JLabel jlbl_nome_cantor_visua;
    private javax.swing.JLabel jlbl_nome_musica;
    private javax.swing.JLabel jlbl_nome_musica_2;
    private javax.swing.JLabel jlbl_nome_musica_visua;
    private javax.swing.JLabel jlbl_remov_visua;
    private javax.swing.JLabel jlbl_title_musica;
    // End of variables declaration//GEN-END:variables
}
